name = "Romangho3"
author = "Rw"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44a4cea14a9bbdb1bcd84f58e74148dfa3ccc2cf82d889f7b47d1e8e15ed2dad"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
