name = "Romangho3"
author = "Rw"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc5a1bfa2d7e47f7c077d2b484acf75f2da1b382478bdaac6b59d41ed8b5b9a5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
